### PR TITLE
Added missing properties to `OpenApiException`

### PR DESCRIPTION
**Pull request by xperiandri**
- Headers
- Content

Content is a crucial property to expose

### CODE REVIEW

**Comment by jkone27** [comment]
i think this file maybe shouldnt be committed ? (to use whatever is available instead of specific version?)
```
Requested SDK version: 7.0.203
global.json file: D:\a\SwaggerProvider\SwaggerProvider\global.json

```

**Comment by xperiandri** [comment]
@jkone27 Fake will fail then if .NET 7 SDK present on a device

**Comment by sergey-tihon** [comment]
Thanks, released as [v2.0.0-theta-001](https://www.nuget.org/packages/SwaggerProvider/2.0.0-theta-001)

**Comment by sergey-tihon** [comment]
> @sergey-tihon would you be interested in an extra parameter on the OpenApiProvider constructor that allows this to be exposed through Result? I'll create a tracking issue and a PR for that. Might be a nice feature to have in v2.0? Or is it too late to add to theta?

@abelbraaksma, go for it if you think it will be useful for you. I am more than happy to merge it and release it to NuGet when it will be ready.

**Pull request merged**
