### PR TITLE
F#6: migration from async{} to task{}

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by Thorium** [comment]
I wouldn't recommend to use task until VS2022 17.3 is released with the fix for the F# compiler, handling task state machine properly. Meanwhile it may not affect this library directly, the users might be affected.

**Comment by Thorium** [comment]
...which was released yesterday.

**Comment by sergey-tihon** [comment]
@Thorium thank you, can you also please point me to bug that was fixed.

One of my tests fails because can't catch exception throw inside `task{}` ... can it be related?

**Comment by Thorium** [comment]
I think it's not, rather async-exceptions are via Async.Catch where task is your traditional AggregateException.

**Pull request merged**
