### PR TITLE
Bye-bye NUnit, hello Expecto!

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Appreciate any advice why FCS may fail when I run it like
`cmd`->`fake`->`expecto`->`FCS`

I do pretty simple thing - I want to test that TP is compilable on known schemas
https://github.com/fsprojects/SwaggerProvider/blob/expecto/tests/SwaggerProvider.ProviderTests/APIs.Guru.FSC.Tests.fs#L32-L33

Log from Travis:
> unknown (1,1)-(1,81) parse error Problem reading assembly '/usr/lib/mono/4.5/mscorlib.dll': Destination array was not long enough. Check destIndex and length, and the array's lower bounds
> startup (1,1)-(1,81) parse error internal error: BuildFoundationalTcImports: no ccu for mscorlib.dll

Log from AppVeyor:
>System.Exception: Compilation error:
unknown (1,1)-(1,81) parse error Error opening binary file 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.dll': Object reference not set to an instance of an object.
unknown (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.dll': Error opening binary file 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Xml.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Runtime.Remoting.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Runtime.Serialization.Formatters.Soap.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Data.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Drawing.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Core.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Runtime.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Linq.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Reflection.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Linq.Expressions.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Threading.Tasks.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.IO.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Net.Requests.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Collections.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Runtime.Numerics.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Threading.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Web.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Web.Services.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Windows.Forms.dll': Object reference not set to an instance of an object.
startup (1,1)-(1,81) parse error Problem reading assembly 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Numerics.dll': Object reference not set to an instance of an object.
unknown (1,1)-(1,81) parse error internal error: BuildFrameworkTcImports: no successful import of C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.dll


// cc @forki @7sharp9 @dungpa @enricosada @ncave @cloudRoutine @haf

**Comment by sergey-tihon** [comment]
The local behavior is also strange ...
Sometimes I see the exact AppVeyor behavior, sometimes concurrent issues ( I do no run tests in parallel)

image
image

**Comment by enricosada** [comment]
@sergey-tihon i think i fixed it with https://github.com/fsprojects/SwaggerProvider/pull/63

i seen multiple `test starting` before `passing`, so i think it is because test are not run sequentially.

i seen the `--sequentially` arg in build script, but never used expecto before, so maybe is not enough (or just for benchmark?) /cc @haf

**Comment by haf** [comment]
It's `--sequenced`, not sequentially.

Seems to be a race condition in the compiler that gets triggered.

**Comment by haf** [comment]
Nice, that seems to have fixed the race.

**Comment by enricosada** [comment]
@haf i am really impressed by expecto. never tried before, but was easy to fix this bug. 
Simple design and good doc.
And i love just adding `|> testSequenced` to specify parallelism

BTW i think there is a bug in fake task, that's executed from FAKE

```
e:\github\SwaggerProvider\tests\SwaggerProvider.ProviderTests\bin\Release\SwaggerProvider.Tests.exe --sequential --filter Integration/
```

generated by 

```fsharp
    !! testAssemblies
    |> Expecto (fun p ->
        { p with
            Parallel = false
            Filter = "Integration/" } )
    |> ignore
```

so maybe is FAKE task wrong using `--sequential`?

**Comment by sergey-tihon** [comment]
I also thought that when I say `parallel  = false` is will be sequential ... // @haf 
My bad, thank you for help @enricosada !

**Comment by forki** [comment]
It's not a bug. It's just a different default.

**Comment by sergey-tihon** [comment]
one more question to Pros...
In this case I have 2 expecto projects, each contains unit tests and integration tests...
total time of execution of unit tests is about 5min and integration tests about 25 min.

right now, fake script execute tests 4 times (unit+integration for each assembly) is any way to reduce number to 2? (with just two test result summaries)

**Comment by enricosada** [comment]
@sergey-tihon well, i was thinking the same as you about parallel = false, to be the right option for that.
but specify `|> testSequenced` is better than cmdline arg anyway, because when added to code is mandatory  always (and works with fsi too)

> just want to minimize number of test summaries
dunno, maybe a final summary (merging result of all test suites execution) can be good. 
there are log files who can be merged, and shown by another command?

**Comment by haf** [comment]
With `testSequenced`, the racy behaviour is clearly delineated in code.

**Comment by enricosada** [comment]
> With testSequenced, the racy behaviour is clearly delineated in code

thx @haf, i was searching for these exact words!

**Pull request merged**
