### PR TITLE
[WIP] most of the grunt work to get httpclient integrated

### PR DESCRIPTION
**Pull request by baronfel**
This doesn't do all of what we want in #100, like hiding the http calls behind the runtime-specific client class, but it brings in the HttpClient dependency and threads through most of the logic that would be needed in the OperationCompiler anyway. Moving to the runtime-specific client class would mostly be a matter of changing the actual call to the static httpclient in operationCompiler to a call to `SendAsync` or the appropriate call on our client wrapper class.

I _think_ I was having build issues locally, so part of this is just to see if the build servers are happier with this than my local machine is.

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Error messages like 
```
error FS3033: The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error: unknown constant '<fun:httpMethodForRestCall@158-1>' of type '<StartupCode$SwaggerProvider-DesignTime>.$OperationCompiler+httpMethodForRestCall@158-1' in generated method. You may need to avoid variable capture in a quotation specifying a type provider. 
```
means that we should not call methods defined in design-time assembly from provided quotation.

So, all building blocks should be moved to runtime assembly.

@baronfel would you like to move them?

**Comment by sergey-tihon** [comment]
> [23:28:31 ERR] All/Swashbuckle.UpdateControllers.Tests/Update Array Int POST Test errored in 00:00:00.0990000 <Expecto>
System.NotSupportedException: Specified method is not supported.
  at Lambda77b383a1-35e4-47ed-84cf-eddba544373c.Invoke (Microsoft.FSharp.Core.Unit ) [0x001af] in <5a8c84ea3a16bde5a7450383ea848c5a>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@522[b,a].Invoke (Microsoft.FSharp.Control.AsyncParams`1[T] args) [0x00051] in <5a7d678a904cf4daa74503838a677d5a>:0

generated code 
```csharp
      public FSharpAsync<int[]> PostApiUpdateArrayInt(int[] x)
      {
        FSharpFunc<FSharpAsync<object>, object> fsharpFunc = Swagger.Internal.RuntimeHelpers.get_asyncCast().Invoke(typeof (int[]));
        Lambdad92d1b9e\u002D8d77\u002D4787\u002D8a44\u002Dc9f992846b21 obj = new Lambdad92d1b9e\u002D8d77\u002D4787\u002D8a44\u002Dc9f992846b21();
        obj.@this = this;
        obj.x = x;
        FSharpAsyncBuilder defaultAsyncBuilder = ExtraTopLevelOperators.DefaultAsyncBuilder;
        FSharpAsync<object> func = ((FSharpFunc<FSharpAsyncBuilder, FSharpAsync<object>>) obj).Invoke(defaultAsyncBuilder);
        return (FSharpAsync<int[]>) fsharpFunc.Invoke(func);
      }
```

**Comment by sergey-tihon** [comment]
Interesting... What is exactly not supported =)

**Comment by baronfel** [comment]
How did you dump the generated code? did you find the temporary assembly on-disk and use ildasm/dotpeek on it?

**Comment by baronfel** [comment]
The errors I get now are all related to an unsupported subtraction operator call:

```
[09:28:27 ERR] All/Swashbuckle.ReturnControllers.Tests/Return Object Point POST Test errored in 00:00:00.0050000 <Expecto>
System.NotSupportedException: Specified method is not supported.
   at Microsoft.FSharp.Core.Operators.op_Subtraction[T1,T2,T3](T1 x, T2 y)
   at Lambdaa27c5b4a-112c-4b9b-beca-9a0989c45239.Invoke(Unit )
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
```

**Comment by sergey-tihon** [comment]
Compiler merges temp assembly to target assembly, so these samples dotpeek'ed from `SwaggerProvider.ProviderTests.dll`

**Comment by baronfel** [comment]
Thanks, that gives me enough information to do some digging on my own.

**Comment by sergey-tihon** [comment]
One more error message (this time from Window)

> [13:29:22 ERR] All/Swashbuckle.ResourceControllers.Tests/ResourceStringString Update value in the resource dictionary errored in 00:00:00.1470000 <Expecto>
System.NotSupportedException: Specified method is not supported.
   at Microsoft.FSharp.Core.Operators.op_Subtraction[T1,T2,T3](T1 x, T2 y)
   at Lambda30cb63ff-f943-4fb8-8bb4-125c35c8a163.Invoke(Unit )
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)

and the code of `Lambda30cb63ff-f943-4fb8-8bb4-125c35c8a163.Invoke(Unit )` ILSpy'ed

```csharp
using Microsoft.FSharp.Collections;
using Microsoft.FSharp.Control;
using Microsoft.FSharp.Core;
using Swagger.Internal;
using System;
using System.Net.Http;
using System.Text;
using System.Text.RegularExpressions;

internal class Lambda30cb63ff-f943-4fb8-8bb4-125c35c8a163 : FSharpFunc<Unit, FSharpAsync<Unit>>
{
	internal FSharpAsyncBuilder builder@;

	internal string key;

	internal SwashbuckleReturnControllersTests.WebAPI.Client @this;

	internal string value;

	public sealed override FSharpAsync<Unit> Invoke(Unit P_0)
	{
		FSharpAsyncBuilder fSharpAsyncBuilder = this.builder@;
		string text = this.key;
		SwashbuckleReturnControllersTests.WebAPI.Client client = this.@this;
		string text2 = this.value;
		FSharpAsyncBuilder fSharpAsyncBuilder2 = fSharpAsyncBuilder;
		StringContent stringContent = new StringContent(RuntimeHelpers.serialize.Invoke((object)text2), Encoding.UTF8, "application/json");
		UriBuilder uriBuilder = new UriBuilder(RuntimeHelpers.combineUrl(((ProvidedSwaggerBaseType)client).Host, Regex.Replace("/api/ResourceStringString/{key}", "{key}", ((object)text).ToString())));
		Lambdad5a343e1-86df-4083-986b-2e426dc32573 lambdad5a343e1-86df-4083-986b-2e426dc = new Lambdad5a343e1-86df-4083-986b-2e426dc32573();
		FSharpFunc<Tuple<string, string>, string> mapping = new Lambda06ae4daf-22d3-4ffa-827f-9028b83fe252();
		string text3 = lambdad5a343e1-86df-4083-986b-2e426dc.Invoke(new Lambda816af573-5b74-455c-ab88-2ecd5f855dd0
		{
			mapping = mapping
		}.Invoke(FSharpList<Tuple<string, string>>.Empty));
		if (string.IsNullOrEmpty(uriBuilder.Query))
		{
			uriBuilder.Query = text3;
		}
		else
		{
			uriBuilder.Query = string.Format("{0}&{1}", (object)uriBuilder.Query, (object)text3);
		}
		Uri uri = uriBuilder.Uri;
		HttpMethod method = new HttpMethod("PUT");
		HttpRequestMessage httpRequestMessage = new HttpRequestMessage(method, uri);
		FSharpFunc<Tuple<string, string>, bool> predicate = new Lambdaf994f006-bf1f-4214-b467-a497daba022a();
		bool flag = new Lambda8bb67850-4e78-435c-bc44-59d57d006a76
		{
			predicate = predicate
		}.Invoke(((ProvidedSwaggerBaseType)client).Headers);
		Tuple<string, string>[] array = (!Operators.Not(flag) || 1 == 0) ? ((ProvidedSwaggerBaseType)client).Headers : ArrayModule.Append(new Tuple<string, string>[1]
		{
			new Tuple<string, string>("Content-Type", "application/json")
		}, ((ProvidedSwaggerBaseType)client).Headers);
		int num = 0;
		while (true)
		{
			if (num > ArrayModule.Length(array) - 1)
			{
				break;
			}
			Tuple<string, string> array2 = LanguagePrimitives.IntrinsicFunctions.GetArray(array, num);
			string item = array2.Item2;
			string item2 = array2.Item1;
			httpRequestMessage.Headers.Add(item2, item);
			num++;
		}
		HttpRequestMessage httpRequestMessage2 = httpRequestMessage;
		httpRequestMessage2.Content = (HttpContent)stringContent;
		HttpRequestMessage message = new Lambda3a7f3438-b2c7-4c4a-b462-3d1f1425d04d
		{
			@this = client
		}.Invoke(httpRequestMessage2);
		return fSharpAsyncBuilder2.Bind(RuntimeHelpers.sendMessage(message), new Lambda9528c2a3-90fe-444c-9e82-4e1ab737d311
		{
			builder@ = fSharpAsyncBuilder
		});
	}
}
```

not so much options where `Microsoft.FSharp.Core.Operators.op_Subtraction[T1,T2,T3](T1 x, T2 y)` could be... the only place is the `while` loop
```csharp
              while (true)
		{
			if (num > ArrayModule.Length(array) - 1)
			{
```

This is `IL` of provided code 
```il
IL_0167: stloc.s 12
IL_0169: ldc.i4.0
IL_016a: stloc.s 15
// loop start (head: IL_016c)
    IL_016c: ldloc.s 15
    IL_016e: ldloc.s 12
    IL_0170: call int32 [FSharp.Core]Microsoft.FSharp.Collections.ArrayModule::Length<class [mscorlib]System.Tuple`2<string, string>>(!!0[])
    IL_0175: ldc.i4.1
    IL_0176: call !!2 [FSharp.Core]Microsoft.FSharp.Core.Operators::op_Subtraction<int32, int32, int32>(!!0, !!1)
    IL_017b: bgt.s IL_01b2

    IL_017d: ldloc.s 12
    IL_017f: ldloc.s 15
    IL_0181: call !!0 [FSharp.Core]Microsoft.FSharp.Core.LanguagePrimitives/IntrinsicFunctions::GetArray<class [mscorlib]System.Tuple`2<string, string>>(!!0[], int32)
    IL_0186: stloc.s 16
    IL_0188: ldloc.s 16
    IL_018a: call instance !1 class [mscorlib]System.Tuple`2<string, string>::get_Item2()
    IL_018f: stloc.s 17
    IL_0191: ldloc.s 16
    IL_0193: call instance !0 class [mscorlib]System.Tuple`2<string, string>::get_Item1()
    IL_0198: stloc.s 18
    IL_019a: ldloc.s 11
    IL_019c: call instance class [System.Net.Http]System.Net.Http.Headers.HttpRequestHeaders [System.Net.Http]System.Net.Http.HttpRequestMessage::get_Headers()
    IL_01a1: ldloc.s 18
    IL_01a3: ldloc.s 17
    IL_01a5: call instance void [System.Net.Http]System.Net.Http.Headers.HttpHeaders::Add(string, string)
    IL_01aa: ldloc.s 15
    IL_01ac: ldc.i4.1
    IL_01ad: add
    IL_01ae: stloc.s 15
    IL_01b0: br.s IL_016c
// end loop
```

At this point, I really need some ideas or advice, because I do not see the issue ...

@dsyme  please take a look if you have a moment. The compilation is successful, but in the runtime provided code fails.

**Comment by sergey-tihon** [comment]
### Summary 

TPSDK can compile the for loop over spliced array, but generated code is incorrect
```
 <@
       ...
       for (name, value) in %heads do msg.Headers.Add(name, value)
       msg 
                @>
```

as workaround we could replace for loop by `Seq.iter`

```fsharp
<@
     %heads
     |> Seq.iter (fun (name, value) ->
          msg.Headers.Add(name, value)
      )
                    msg 
                @>
```

@dsyme do you understand the reason? Could we fix it or should we update docs or improve error message? thx

**Pull request merged**
