### PR TITLE
.NET 6

### PR DESCRIPTION
**Pull request by sergey-tihon**
- [x] Building .NET 6
- [x] Drop support of full .net framework https://github.com/fsprojects/SwaggerProvider/issues/165
- [x] Migrating to System.Text.Json  https://github.com/fsprojects/SwaggerProvider/pull/176
- [ ] Simplify project files, build and NuGet packaging

### CODE REVIEW

**Comment by xperiandri** [comment]
`warning NU1603: SwaggerProvider 1.0.0-beta1 depends on FSharp.SystemTextJson (>= 0.16.0 && < 1.0.0) but FSharp.SystemTextJson 0.16.0 was not found. An approximate best match of FSharp.SystemTextJson 0.16.6 was resolved.`

**Comment by colelawrence** [comment]
Hi, I'm not sure if this is the right place to put my question, but I'm seeing a similar issue as above with the Type Provider in a .net5 project freshly started with minimal dependencies:

```
<PackageReference Include="SwaggerProvider" Version="1.0.0-beta2" />
```

```
The type provider 'SwaggerProvider.OpenApiClientTypeProvider' reported an error: Could not load file or assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
```
image

**Comment by xperiandri** [comment]
@colelawrence, Rider? We haven't tested with it

**Comment by hkrutzer** [comment]
I also get this error, in Rider.

**Comment by colelawrence** [comment]
@xperiandri, thanks for asking. Yes, this is in Rider

**Comment by sergey-tihon** [comment]
@colelawrence @hkrutzer can you share repro steps?
Just created new console .net 5 app using Rider 2021.1 EAP6 at looks OK on my machine.

TestSwagger_–_Program_fs

**Comment by jkone27** [comment]
Is this gonna be merged soon? Or is it gonna be to NET7 instead? probably NET5 is LTS and NET7 is LTS also

**Comment by sergey-tihon** [comment]
@jkone27 .NET 6 is LTS (5 & 7 are not). All changes from this branch available in latest beta. Does it works for you?

**Comment by jkone27** [comment]
ah i got confused on LTS sorry then! yes happily using the latest beta!

**Pull request merged**
