### PR TITLE
NTLM auth for schema request

### PR DESCRIPTION
**Pull request by sergey-tihon**
Fix for #50

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@vasily-kirichenko Is it what you potentially need?

**Comment by vasily-kirichenko** [comment]
I was creating a PR with same patch :)

**Comment by vasily-kirichenko** [comment]
Yes, this patch works great. Thanks for your time!

**Comment by vasily-kirichenko** [comment]
Could you please release fresh NuGet package?

**Pull request merged**
