### PR TITLE
build and test with .net 8

### PR DESCRIPTION
**Pull request by sergey-tihon**
@Thorium do you use .net 6 or .net 8?

### CODE REVIEW

**Comment by Thorium** [comment]
Mixed, I really don't mind: 
- I usually use F# 8 and target on .NET Standard (2.0 and 2.1), the .NET version doesn't matter too much. The actual .NET is just for build and running tests, right?
- But I also have old projects on .NET Framework 4.8 which do work well with F# 8 and .NET Standard 2.0

**Comment by Thorium** [comment]
Initial test of this branch:
- `dotnet build` works for SwaggerProvider.sln
- `dotnet test` cannot find tests in SwaggerProvider.sln
- `dotnet build` fails for SwaggerProvider.TestsAndDocs.sln (I'm not running anything on localhost:5000)
- `build.cmd` fails
    > Fake cache failed, please consider reporting a bug: System.Exception: Cache is invalid as 'Microsoft.CSharp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' doesn't exist

**Comment by sergey-tihon** [comment]
Just run `./build.sh` if you want to build locally, or test it from NuGet https://www.nuget.org/packages/SwaggerProvider/2.1.0-beta1

**Comment by sergey-tihon** [comment]
@Thorium if beta1 works for you, I can quickly release it as 2.1.0

**Comment by Thorium** [comment]
I don't see why it wouldn't there are no actual changes to the code (the ProvidedTypes didn't have anything that would affect, and I already use FSharp.Core 8 with the current one).

The NuGet package says dependency to FSharp.Core > 6.0.7 meanwhile the software itself as been built with FSharp.Core 8.0.200.
I don't know if it's good or bad these not to match: Basically people may still be hanging on some old FSharp.Core for no obvious reason (except that the working  hours for technical update of FSharp.Core doesn't give any business revenue) and there the relaxed condition makes it easier for people to update, but then again, can it cause issues, I don't know.

**Comment by sergey-tihon** [comment]
I am worry about `/typeproviders/fsharp41/net8.0/` files

image

**Pull request merged**
