### PR TITLE
[WIP] On the way to v1.0

### PR DESCRIPTION
**Pull request by sergey-tihon**
- [x] SwaggerParser moved to runtime assembly (and exposed as API to library users) - #90 
- [x] Removed dependency on FSharp.Data/JsonValue (replaced by JSON.NET)
- [x] Provide full-init constructor - #91
- [x] Option/Nullable types for not required properties - #93
- [x] Fix issue in FSI - #94 
- [x] Support namespaces in type names #96 
- [x] Replace `FSharp.Data/src/Net/Http.fs` by `HttpClient` from BCL #100
    - [ ] Do use `async` inside provided methods, everything should be `Task`
- [x] Provide Async & Task API - #21
- [x] Revise operation naming rules - #45 
- [x] Migrate to Microsoft.OpenApi.Readers - #98 
   - [ ] Support ref to relative files ? - https://github.com/APIs-guru/openapi-directory/issues/351
- [ ] Default values for optional ctor params for C#
- [ ] Test naming conventions used by [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle)
- [ ] Fix/test TP execution on Mono (there are issues with System.Net.Http) - https://github.com/dotnet/corefx/issues/19914
- [ ] Test performance on [large schemas](https://github.com/fsprojects/SwaggerProvider/pull/88#issuecomment-338367178) / think about caching
- [ ] Enable FSI tests
- [ ] Update docs and site #127

### CODE REVIEW

**Comment by baronfel** [comment]
I have most of the work done for http clients as well that I'll start a PR for later today, I hope. The plumbing is done and I'm just working through runtime errors trying to find the underlying assembly in the runtime assembly resolution set.

**Comment by sergey-tihon** [comment]
you may want to look at the draft of new base class for the Client https://github.com/fsprojects/SwaggerProvider/blob/dev/src/SwaggerProvider.Runtime/SwaggerApiClient.fs or delete if you do the better one.

I hope that HttpClient will help to fix #59

**Comment by baronfel** [comment]
I saw that and was curious about it for sure. There are two things we have to do correctly when using HttpClient:

1. don't Dispose them (they hang around for ~2 minutes with a TCP socket open)
2. don't use a singleton instance (DNS queries stick for each HttpMessageHandler (which the HttpClient uses under the hood)), and instead refresh it every so often (5 minutes?)

**Comment by baronfel** [comment]
Looking at the WIP list for this issue, I think I see the optional parameters for C# constructors in the code already.

```fsharp
           ty.AddMember <|
                ProvidedConstructor(
                    [ProvidedParameter("host", typeof<string>, optionalValue = defaultHost)],
                    invokeCode = (fun args ->
                        match args with
                        | [] -> failwith "Generated constructors should always pass the instance as the first argument!"
                        | _ -> <@@ () @@>),
                    BaseConstructorCall = fun args -> (baseCtor, args))
```

specifically the `optionalValue` property. Is that correct?

**Comment by sergey-tihon** [comment]
@baronfel IIRC it does not work from C#...

We use optional params in provided types init ctor and in provided methods
https://github.com/fsprojects/SwaggerProvider/blob/dev/tests/SwaggerProvider.ProviderTests.CSharp/Program.cs#L17

**Comment by baronfel** [comment]
ah, ok! That is a good example 👍 (In case you couldn't tell I'm looking at things to work on :))

**Comment by sergey-tihon** [comment]
If you have a prototype for `Replace FSharp.Data/src/Net/Http.fs by HttpClient from BCL` - please open PR. This is one of two big items that I would love to see in 1.0

**Comment by baronfel** [comment]
It is....lacking after the conversation we had in the other issue thread, but thanks for the reminder. I'll tinker with that against starting tomorrow!

**Comment by panesofglass** [comment]
@sergey-tihon will you be renaming this, at least in the docs, as Open API Provider? Also, it looks like this will now be 2 & 3 compliant, right?

**Comment by sergey-tihon** [comment]
@panesofglass It will compliant with `v3` after migration to `OpenApi.NET` (that is not done yet). After that, we can adjust documentation, but I am not sure if we should rename NuGet package or not...

**Comment by ctaggart** [comment]
So that plan is to use the readers from https://github.com/Microsoft/OpenAPI.NET https://www.nuget.org/packages/Microsoft.OpenApi.Readers ?

**Comment by ctaggart** [comment]
Yes it is. I found the issue for Microsoft.OpenApi.Readers: https://github.com/fsprojects/SwaggerProvider/issues/98

**Comment by sergey-tihon** [comment]
This is really old PR and for sure is not fully implemented (not 1.0 yet)
But in order to simplify branching, I decided to merge it in master and track all improvements as separate issues

**Pull request merged**
